name: pull_request_testing

on:
  pull_request:
    types:
      - labeled
      - opened
    branches:
    - main
  workflow_dispatch:

jobs:
  workflow_handler:
    runs-on: ubuntu-22.04
    steps:
    - name: debug
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Verification
      uses: actions/github-script@v6.4.0
      with:
        script: |

          console.log("${{ github.event_name }}")
          if ("${{ github.event_name  }}" === "workflow_dispatch") {
            console.log("starting job from workflow dispatch")
          }
          else if ("${{ github.event.action }}" === "opened") {
            console.log("starting job from pull request creation")
          }
          else if ("${{ github.event.action }}" === "labeled" && "${{ github.event.label.name }}" == "RUN AUTOTESTER") {
            console.log("starting job from label")
          }
          else {
            core.setFailed("not running job")
          }
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
        all_but_latest: true
    - name: Remove "RUN AUTOTESTER" Label
      uses: actions-ecosystem/action-remove-labels@v1.3.0
      with:
        labels: RUN AUTOTESTER
    - name: Set "TESTING..." Label
      uses: actions-ecosystem/action-add-labels@v1.1.0
      with:
        labels: TESTING...
        github_token: ${{ github.token }}
  test_pr:
    runs-on: self-hosted
    needs: workflow_handler
    steps:
    - name: hpc build simulation
      run: echo "RUNNING ON HPC MACHINE"
