name: pull_request_testing

on:
  pull_request:
    types:
      - labeled
      - opened
    branches:
    - master
  workflow_dispatch:

jobs:
  workflow_handler:
    runs-on: ubuntu-22.04
    steps:
    - name: TODO
      run: echo "TODO"
  test_pr:
    runs-on: self-hosted
    steps:
    - name: TODO
      run: echo "TODO"
